### ISSUE TITLE
Replace reference to AEM_DIR_CORE in bootstrap.sh comment

### ISSUE THREAD

**Issue by aweinert-MIT** [rearley516/Flood-Analysis#4]
https://github.com/rearley516/Flood-Analysis/blob/8fe876879e9eaf2f58c28748a64992d7c3fc2b75/scripts/bootstrap.sh#L21

**Comment by rearley516** [comment]
comment edited to reflect the use of FLOOD_ANALYSIS_CORE instead of AEM_DIR_CORE
